name: dannce
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2023.07
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiobotocore=2.5.0
  - aiofiles=22.1.0
  - aiohttp=3.8.3
  - aioitertools=0.7.1
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - alabaster=0.7.12
  - anaconda-catalogs=0.2.0
  - anaconda-client=1.11.3
  - anaconda-project=0.11.1
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - arrow-cpp=11.0.0
  - astroid=2.14.2
  - astropy=5.1
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - automat=20.2.0
  - autopep8=1.6.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - bokeh=3.1.1
  - boltons=23.0.0
  - boost-cpp=1.73.0
  - botocore=1.29.76
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - c-blosc2=2.8.0
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - clyent=1.2.2
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.2
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.1.0
  - conda-package-streaming=0.8.0
  - conda-repo-cli=1.0.41
  - conda-verify=3.4.2
  - constantly=15.1.0
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=39.0.1
  - cssselect=1.1.0
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - curl=8.1.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - daal4py=2023.1.1
  - dal=2023.1.1
  - dask=2023.6.0
  - dask-core=2023.6.0
  - datashader=0.15.0
  - datashape=0.5.4
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - distributed=2023.6.0
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3
  - filelock=3.9.0
  - flake8=6.0.0
  - flask=2.2.2
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - future=0.18.3
  - gensim=4.3.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - greenlet=2.0.1
  - grpc-cpp=1.46.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.16.2
  - hvplot=0.8.4
  - hyperlink=21.0.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - imagesize=1.4.1
  - imbalanced-learn=0.10.1
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - incremental=21.3.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.8
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - joblib=1.2.0
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lazy_loader=0.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.6.2
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.0.149
  - libcurand=10.3.3.53
  - libcurl=8.1.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - liblief=0.12.3
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libmamba=1.4.1
  - libmambapy=1.4.1
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsolv=0.7.22
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvmlite=0.40.0
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=4.1.1
  - mpmath=1.2.1
  - msgpack-python=1.0.3
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.7
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numba=0.57.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - numpydoc=1.5.0
  - oniguruma=6.9.7.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=1.1.1u
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - panel=1.1.0
  - param=1.13.0
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - patch=2.7.6
  - patchelf=0.17.2
  - pathlib=1.0.1
  - pathspec=0.10.3
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.37
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pkginfo=1.9.6
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=8.0.0
  - py-lief=0.12.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.2
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pyodbc=4.0.34
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.8.0
  - pytest=7.3.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-libarchive-c=2.9
  - python-lmdb=1.4.1
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - python-snappy=0.6.1
  - python-xxhash=2.0.2
  - pytoolconfig=1.2.5
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyviz_comms=2.3.0
  - pywavelets=1.4.1
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - queuelib=1.5.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests-file=1.5.1
  - requests-toolbelt=0.9.1
  - responses=0.13.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rope=1.7.0
  - rtree=1.0.1
  - ruamel.yaml=0.17.21
  - ruamel_yaml=0.17.21
  - s3fs=2023.4.0
  - sacremoses=0.0.43
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scikit-learn-intelex=2023.1.1
  - scipy=1.10.1
  - scrapy=2.8.0
  - secretstorage=3.3.1
  - send2trash=1.8.0
  - service_identity=18.1.0
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - spyder-kernels=2.4.3
  - sqlalchemy=1.4.39
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tabulate=0.8.10
  - tbb=2021.8.0
  - tbb4py=2021.8.0
  - tblib=1.7.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - tldextract=3.2.0
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.2
  - traitlets=5.7.1
  - twisted=22.10.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - ujson=5.4.0
  - unidecode=1.2.0
  - unixodbc=2.3.11
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - w3lib=1.21.0
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - whatthepatch=1.0.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xarray=2022.11.0
  - xxhash=0.8.0
  - xyzservices=2022.9.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yapf=0.31.0
  - yarl=1.8.1
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=5.4.0
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.34.2
      - anndata==0.10.5.post1
      - antlr4-python3-runtime==4.11.0
      - array-api-compat==1.4.1
      - astunparse==1.6.3
      - cachetools==5.3.1
      - dataproperty==1.1.0
      - datasets==4.0.0
      - evaluate==0.4.5
      - fasteners==0.18
      - flatbuffers==23.5.26
      - fsspec==2025.3.0
      - gast==0.5.4
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - igraph==0.11.4
      - ipdb==0.13.13
      - jax==0.4.16
      - jaxlib==0.4.16
      - jsonlines==4.0.0
      - keras==2.14.0
      - latentcor==0.2.4
      - latex2sympy2-extended==1.10.2
      - leidenalg==0.10.2
      - libclang==16.0.6
      - lm-eval==0.4.8
      - math-verify==0.8.0
      - mbstrdecoder==1.1.4
      - ml-dtypes==0.2.0
      - natsort==8.4.0
      - numdifftools==0.9.41
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - orthpol-light==2.0.2
      - pathvalidate==3.3.1
      - peft==0.17.1
      - portalocker==3.2.0
      - protobuf==4.24.4
      - pyarrow==21.0.0
      - pybind11==3.0.1
      - pynndescent==0.5.11
      - pytablewriter==1.2.1
      - python-igraph==0.11.4
      - requests==2.32.5
      - requests-oauthlib==1.3.1
      - rouge-score==0.1.2
      - rsa==4.9
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scanpy==1.9.8
      - seaborn==0.13.2
      - semilattices==1.0.1
      - session-info==1.0.0
      - spectraltoolbox==2.0.3
      - sqlitedict==2.1.0
      - stdlib-list==0.10.0
      - tabledata==1.3.4
      - tcolorpy==0.1.7
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - texttable==1.7.0
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.49.0
      - transportmaps==3.0.8
      - typepy==1.3.4
      - umap-learn==0.5.5
      - word2number==1.1
