seed: 42
nd: 4
nw: 512
var_ref: 0.5
lr: 0.0002
lr_step: 10000
lr_gamma: 0.5
log_step : 500
rho: 1.0
nu: 5
bs: 10000
iter_num: 30000
stop_threshold: 12000
repetition_num: 5
output_dir: 'results/Shuttle/Shuttle_evaluation.csv'