seed: 42
nd: 3
nw: 16
output_scale: 2
var_ref: 0.5
lr: 0.0002
log_step : 500
sample_size: 20000
nu: 5
bs: 1024
iter_num: 50000
precision: 100
repetition_num: 20
x_interval: [-1.5, 1.5]
y_interval: [-1.5, 1.5]
output_dir: 'results/indep_gmm/indep_GMM_'